Django/airline/airline/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls")),
]

Django/airline/flights/urls.py
from django.urls import path

from flights import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book"),
]

Django/airline/users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

Django/airline/flights/models.py
from django.db import models
from django.db.models.deletion import CASCADE


# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self) -> str:
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.id}: {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return (self.origin != self.destination) and self.duration > 0


class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self) -> str:
        return f"{self.first} {self.last}"

Django/airline/users/models.py
from django.db import models

# Create your models here.

Django/airline/flights/forms.py
from django import forms
from flights.models import Passenger


class NewPassenger(forms.Form):
    passenger = forms.ModelChoiceField(queryset=None)

    def __init__(self, flight_id: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["passenger"].queryset = Passenger.objects.exclude(flights=flight_id)

Django/airline/users/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    password = forms.CharField(
        label="Password", widget=forms.PasswordInput, help_text="Keep it safe!"
    )

Django/airline/flights/views.py
from django.http import HttpResponseBadRequest, Http404
from django.http.request import HttpRequest
from django.shortcuts import redirect, render

from .models import Flight, Passenger


# Create your views here.
def index(request: HttpRequest):
    return render(request, "flights/index.html", {"flights": Flight.objects.all()})


def flight(request: HttpRequest, flight_id: int):
    try:
        flight = Flight.objects.get(id=flight_id)
    except Flight.DoesNotExist:
        raise Http404("Flight not found.")
    return render(
        request,
        "flights/flight.html",
        {
            "flight": flight,
            "passengers": flight.passengers.all(),
            "non_passengers": Passenger.objects.exclude(flights=flight).all(),
        },
    )


def book(request: HttpRequest, flight_id: int):
    if request.method == "POST":
        try:
            passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
            flight = Flight.objects.get(pk=flight_id)
        except KeyError:
            return HttpResponseBadRequest("Bad Request: no flight chosen")
        except Flight.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: flight does not exist")
        except Passenger.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: passenger does not exist")
        passenger.flights.add(flight)
        return redirect("flights:flight", flight_id)

Django/airline/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm


# Create your views here.
def index(request):
    print(request.user.is_authenticated)
    if not request.user.is_authenticated:
        return redirect("users:login")
    else:
        return render(request, "users/user.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("users:index")
        form = UserForm()
        return render(
            request,
            "users/login.html",
            {"form": form, "message": "Invalid Credentials!"},
        )
    else:
        form = UserForm()

    return render(request, "users/login.html", {"form": form})


def logout_view(request):
    logout(request)
    form = UserForm()
    return render(request, "users/login.html", {"form": form, "message": "Logged Out!"})

Django/airline/flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block title %}
Flight Page
{% endblock title %}


{% block body %}
<h1>Flight {{ flight.id }}</h1>
<h3><a href="{% url 'flights:index' %}">Home</a></h3>

<ul>
  <li>Origin: {{ flight.origin }}</li>
  <li>Destination: {{ flight.destination }}</li>
  <li>Duration: {{ flight.duration }}</li>
</ul>

<h2>Add Passenger</h2>
<form action="{% url 'flights:book' flight.id %}" method="post">
  {% csrf_token %}
  {% include 'flights/form_snippet.html' %}
  <button type="submit">Add Passenger</button>
</form>

<h2>Passengers</h2>
<ul>
  {% for passenger in passengers %}
  <li>{{ passenger }}</li>
  {% empty %}
  No Passengers
  {% endfor %}
</ul>
{% endblock body %}

Django/airline/flights/templates/flights/form_snippet.html
{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}

{# Include the visible fields #}
{% for field in form.visible_fields %}

{{ field.errors }}
{{ field.label_tag }}
{{ field}}

{% if field.help_text %}
<small class="form-text text-muted">{{ field.help_text | safe }}</small>
{% endif %}
{% endfor %}

Django/airline/flights/templates/flights/index.html
{% extends 'flights/layout.html' %}

{% block title %}
Flights
{% endblock title %}

{% block body %}
<h1>Flights</h1>

<ul>
  {% for flight in flights %}
  <li><a href="{% url 'flights:flight'  flight.id %}">Flight {{ flight.id }}: {{ flight.origin }} to
      {{ flight.destination }}</a></li>
  {% endfor %}
</ul>
{% endblock body %}

Django/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} Airline App{% endblock title %}</title>
</head>

<body>
  {% block body %}{% endblock body %}
</body>

</html>