project1/wiki/encyclopedia/urls.py
from django.urls import path

from encyclopedia import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry_page, name="entry_page"),
    path("search_entry", views.search_entry, name="search_entry"),
    path("new_entry", views.new_entry, name="new_entry"),
    path("edit_entry/<entry>", views.edit_entry, name="edit_entry"),
    path("rand_entry", views.rand_entry, name="rand_entry"),
    path("error", views.error, name="error"),
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/views.py
import re
import markdown2 as md2
from django.shortcuts import redirect, render
from django import forms
from random import choice

from encyclopedia import util

# Global variable for error messages
message = ""


# FORMS
class NewEntry(forms.Form):
    title = forms.CharField(
        label="Title", label_suffix="", help_text="Please, keep it short", max_length=20
    )
    content = forms.CharField(
        label="Wiki Content",
        label_suffix="",
        help_text="Your text must be formatted in Markdown",
        widget=forms.Textarea,
    )
    edit_mode = forms.BooleanField(
        initial=False, widget=forms.HiddenInput, required=False
    )


# VIEWS
def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def search_entry(request):
    query = re.compile(request.GET["q"], re.IGNORECASE)
    results = []
    for entry in util.list_entries():
        match = query.search(entry)
        exact_match = query.fullmatch(entry)
        if exact_match:
            return redirect("encyclopedia:entry_page", entry)
        elif match:
            results.append(entry)
    if not results:
        global message
        message = f"Your search - '{request.GET['q']}' - did not match any documents"
        return redirect("encyclopedia:error")

    context = {"results": results}
    return render(request, "encyclopedia/search.html", context)


def entry_page(request, entry):
    if entry not in util.list_entries():
        global message
        message = "Page Not Found 404"
        return redirect("encyclopedia:error")
    entry_html = md2.markdown(util.get_entry(entry))
    context = {"entry_title": entry, "entry_content": entry_html}
    return render(request, "encyclopedia/entry_page.html", context)


def new_entry(request):
    if request.method == "POST":
        # binding data to the form
        form = NewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            edit_mode = form.cleaned_data["edit_mode"]
            entries = map(str.lower, util.list_entries())
            if title.lower() in entries and not edit_mode:
                global message
                message = "A page with this title already exists"
                return redirect("encyclopedia:error")
            util.save_entry(title, content)
            return redirect("encyclopedia:entry_page", title)
        # If form is not valid, we go back to the template with the form.
        # This time the form is no longer empty (unbound) so the HTML form will be
        # populated with the data previously submitted, where it can be edited and
        # corrected as required.
    else:
        form = NewEntry()
    return render(
        request,
        "encyclopedia/new_entry.html",
        {
            "form": form,
            "header_text": "Submit a new entry for the Wiki",
            "btn_text": "Submit Wiki Page",
        },
    )


def edit_entry(request, entry):
    content = util.get_entry(entry)
    form = NewEntry({"title": entry, "content": content, "edit_mode": True})
    return render(
        request,
        "encyclopedia/new_entry.html",
        {
            "form": form,
            "header_text": f"Edit {entry} page of the Wiki",
            "btn_text": "Save Changes",
        },
    )


def rand_entry(request):
    entries = util.list_entries()
    return redirect("encyclopedia:entry_page", choice(entries))


def error(request):
    return render(request, "encyclopedia/error.html", {"message": message})

project1/wiki/encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ entry_title }}
{% endblock %}

{% block body %}
<a href="{% url 'encyclopedia:edit_entry' entry_title %}" class="edit-link">Edit this page</a>
{% block entry %}
{{ entry_content | safe }}
{% endblock entry %}

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}
<h1 class="error-message">{{ message }}</h1>
<hr>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/form_snippet.html
{% load wiki_filters %}

{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}

{# Include the visible fields #}
{% for field in form.visible_fields %}
<div class="form-group">

  {{ field.errors }}
  {{ field.label_tag }}
  {{ field | add_class:'form-control'}}

  {% if field.help_text %}
  <small class="form-text text-muted">{{ field.help_text | safe }}</small>
  {% endif %}
</div>
{% endfor %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
  {% for entry in entries %}
  <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous">
  <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
  <div class="row">
    <div class="sidebar col-lg-2 col-md-3">
      <h2>Wiki</h2>
      <form action="{% url 'encyclopedia:search_entry' %}" method="GET">
        {% csrf_token %}
        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
      </form>
      <div>
        <a href="{% url 'encyclopedia:index' %}">Home</a>
      </div>
      <div>
        <a href="{% url 'encyclopedia:new_entry' %}">Create New Page</a>
      </div>
      <div>
        <a href="{% url 'encyclopedia:rand_entry' %}">Random Page</a>
      </div>
      {% block nav %}
      {% endblock %}
    </div>
    <div class="main col-lg-10 col-md-9">
      {% block body %}
      {% block entry %}
      {% endblock entry %}
      {% endblock body %}
    </div>
  </div>

</body>

</html>

project1/wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Entry
{% endblock %}

{% block body %}

<h1>{{ header_text }}</h1>

<form action="{% url 'encyclopedia:new_entry' %}" method="POST">
  {% csrf_token %}
  {% include 'encyclopedia/form_snippet.html' %}
  <input type="submit" value="{{ btn_text }}" class="btn btn-primary">
</form>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock %}

{% block body %}
<h1>Search Results</h1>
<hr>
<ul>
  {% for entry in results %}
  <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
  {% endfor %}
</ul>

{% endblock %}