project2/commerce/auctions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from auctions import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watch/<int:listing_id>", views.watch, name="watch"),
    path("user_listings/<int:user_id>", views.user_listings, name="user_listings"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category_listing, name="category_listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("watchlist/<int:listing_id>", views.watchlist, name="watchlist"),
    path("new_listing", views.new_listing, name="new_listing"),
    path("listing/<int:listing_id>", views.detail_listing, name="detail_listing"),
    path(
        "listing/<int:listing_id>/comment",
        views.comment_listing,
        name="comment_listing",
    ),
    path("listing/<int:listing_id>/bid", views.bid_listing, name="bid_listing"),
    path("listing/<int:listing_id>/edit", views.edit_listing, name="edit_listing"),
    path("listing/<int:listing_id>/close", views.close_listing, name="close_listing"),
    path("listing/<int:listing_id>/delete", views.delete_listing, name="delete_listing"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Customize 404 error page
# handler404 = 'mysite.views.my_custom_page_not_found_view'

# handler404
# A callable, or a string representing the full Python import path to the view that should be called if none of the URL patterns match.

# By default, this is django.views.defaults.page_not_found(). If you implement a custom view, be sure it accepts request and exception arguments and returns an HttpResponseNotFound.

project2/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("auctions.urls"))]

project2/commerce/auctions/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

# Module for uploaded images
# from .utility import upload_path, file_size, file_ext


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Listing(models.Model):
    title = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=250)
    pub_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    # image = models.ImageField(
    #     blank=True, null=True, upload_to=upload_path, validators=[file_size, file_ext]
    # )
    image = models.URLField(max_length=255, blank=True, null=True)
    vendor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="catalog"
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    bidders = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through="Bid", through_fields=("listing", "user"),
    )

    def __str__(self) -> str:
        return f"{self.title}/Price = ${self.price}"


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="comments"
    )
    post = models.CharField(max_length=250)
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author}"


class Bid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    value = models.DecimalField(null=True, max_digits=9, decimal_places=2)

    def __str__(self) -> str:
        return f"{self.user}/Bid = ${self.value}"


class User(AbstractUser):
    watchlist = models.ManyToManyField(Listing, related_name="watchers")

project2/commerce/auctions/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from auctions.models import Comment, Listing


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ["title", "description", "price", "category", "image"]
        labels = {"price": _("Starting Price"), "image": _("Image URL")}
        help_texts = {
            "title": _("Keep it short"),
            "category": _("Optional"),
            "image": _("Optional"),
        }
        widgets = {
            "description": forms.Textarea(
                attrs={"placeholder": _("Limit of 250 characters."), "rows": 5}
            ),
            # "image": forms.FileInput,
            "price": forms.NumberInput(
                attrs={"max": f"{1000000.00:.2f}", "min": 0.01, "step": "any"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].empty_label = "No Category"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["post"]
        labels = {"post": ""}
        widgets = {
            "post": forms.Textarea(
                attrs={
                    "placeholder": _("Type your comment here. Max of 250 characters."),
                    "rows": 5,
                }
            )
        }


class EditForm(ListingForm):
    class Meta(ListingForm.Meta):
        exclude = ["price"]


class BidForm(forms.Form):
    value = forms.DecimalField(max_digits=9, decimal_places=2)

project2/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http.request import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

from .forms import BidForm, CommentForm, EditForm, ListingForm
from .models import Bid, Category, Listing, User


def index(request: HttpRequest):
    listings = Listing.objects.filter(active=True).order_by("-id")
    return render(request, "auctions/index.html", {"listings": listings})


# * AUTHENTICATION
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user:
            login(request, user)
            return redirect("auctions:index")
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )

    return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return redirect("auctions:index")


def register(request: HttpRequest):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # Ensure password matches confirmation
        if password != confirmation:
            return render(
                request, "auctions/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return redirect("auctions:index")

    return render(request, "auctions/register.html")


def user_listings(request, user_id):
    return render(
        request,
        "auctions/user_listings.html",
        {
            "user_id": user_id,
            "user_listings": User.objects.get(pk=user_id).catalog.all(),
        },
    )


# * CATEGORIES
def categories(request):
    template_rows = 5
    return render(
        request,
        "auctions/categories.html",
        {"rows": template_rows, "categories": Category.objects.all()},
    )


def category_listing(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    listings = category.listing_set.filter(active=True).order_by("-id")

    return render(
        request,
        "auctions/category_listings.html",
        {"name": category.name, "listings": listings},
    )


# * WATCHLIST
@require_POST
def watch(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    watch = int(request.POST["watch"])

    if watch:
        request.user.watchlist.add(listing)
    else:
        request.user.watchlist.remove(listing)

    return redirect("auctions:detail_listing", listing_id)


@login_required
def watchlist(request, listing_id=None):
    if request.method == "POST":
        listing = get_object_or_404(Listing, pk=listing_id)
        request.user.watchlist.remove(listing)
        return redirect("auctions:watchlist")

    return render(
        request, "auctions/watchlist.html", {"watchlist": request.user.watchlist.all()}
    )


# * LISTING MANAGEMENT
def detail_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    comments = listing.comments.all()

    # If there is no bids on the listing, IndexError will be raised
    try:
        highest_bid = listing.bid_set.order_by("-value")[0]
        match_bidder = highest_bid.user == request.user
    except IndexError:
        match_bidder = False

    bid_form = BidForm()
    comment_form = CommentForm()

    return render(
        request,
        "auctions/detail_listing.html",
        {
            "bid_form": bid_form,
            "comments": comments,
            "comment_form": comment_form,
            "listing": listing,
            "match_bidder": match_bidder,
        },
    )


@require_POST
def comment_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.listing = listing
        comment.save()
        return redirect("auctions:detail_listing", listing_id)

    try:
        highest_bid = listing.bid_set.order_by("-value")[0]
        match_bidder = highest_bid.user == request.user
    except IndexError:
        match_bidder = False

    return render(
        request,
        "auctions/detail_listing.html",
        {
            "bid_form": BidForm(),
            "comments": listing.comments.all(),
            "comment_form": form,
            "listing": listing,
            "match_bidder": match_bidder,
        },
    )


@require_POST
def bid_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)

    # Check listing for any biddings
    try:
        highest_bid = listing.bid_set.order_by("-value")[0]
        match_bidder = highest_bid.user == request.user
    except IndexError:
        highest_bid = False
        match_bidder = False

    value = float(request.POST["value"])
    form = BidForm(request.POST)

    # Check if input value is higher than current bid on active listing
    if form.is_valid() and value > listing.price and listing.active:
        bid = Bid.objects.get_or_create(user=request.user, listing=listing)[0]
        bid.value = form.cleaned_data["value"]
        listing.price = form.cleaned_data["value"]
        listing.save()
        bid.save()
        return redirect("auctions:detail_listing", listing_id)

    # Block biddings on closed listing
    elif not listing.active and highest_bid:
        closed = ValidationError(
            _("This listing is closed.\n%(winner)s won the auction."),
            code="closed",
            params={"winner": highest_bid.user},
        )
        form.add_error(field="value", error=closed)

    else:
        bid_lower = ValidationError(
            _("Bid must be higher than $%(price)s"),
            code="bid_lower",
            params={"price": listing.price},
        )
        form.add_error(field="value", error=bid_lower)

    return render(
        request,
        "auctions/detail_listing.html",
        {
            "bid_form": form,
            "comments": listing.comments.all(),
            "comment_form": CommentForm(),
            "listing": listing,
            "match_bidder": match_bidder,
        },
    )


@login_required
def new_listing(request):
    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            # Retrieve Model from the Form without committing to database
            listing = form.save(commit=False)
            listing.vendor = request.user
            listing.save()
            # After registering the user as the vendor, ManyToMany Field needs to be saved manually if commit=False
            form.save_m2m()
            return redirect("auctions:index")
        else:
            return render(request, "auctions/new_listing.html", {"form": form})

    form = ListingForm()
    return render(request, "auctions/new_listing.html", {"form": form})


@login_required
def edit_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)

    if request.method == "POST":
        form = EditForm(request.POST, request.FILES, instance=listing)
        if form.is_valid():
            form.save()
            return redirect("auctions:index")
        else:
            # listing is updated with request.POST data in form.is_valid()
            # even if the form is not valid, so the object must be repopulated from the DB
            listing.refresh_from_db()
            return render(
                request,
                "auctions/edit_listing.html",
                {"form": form, "listing": listing},
            )

    form = EditForm(instance=listing)
    return render(
        request, "auctions/edit_listing.html", {"form": form, "listing": listing}
    )


@login_required
def close_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    listing.active = False
    listing.save()

    # Check listing for biddings
    try:
        winner = listing.bid_set.order_by("-value")[0].user
    except IndexError:
        winner = False

    # Add listing to winner's watchlist
    if winner and listing not in winner.watchlist.all():
        winner.watchlist.add(listing)

    return redirect("auctions:detail_listing", listing_id)


@login_required
def delete_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    listing.delete()
    return redirect("auctions:user_listings", request.user.id)

project2/commerce/auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/links.css' %}">
{% endblock styles %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link1="active" %}
{% endblock nav %}

{% block body %}

<div class="row">
  {% for category in categories %}

  {% if forloop.counter0 == 0 or forloop.counter0|divisibleby:rows %}
  <div class="col-auto">
    <div class="list-group">
      {% endif %}

      <a class="list-group-item list-group-item-action mb-2"
         href="{% url 'auctions:category_listing' category.id %}">{{ category }}</a>

      {% if forloop.counter|divisibleby:rows %}
    </div>
  </div>
  {% endif %}

  {% endfor %}

</div>

{% endblock body %}

project2/commerce/auctions/templates/auctions/category_listings.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/links.css' %}">
{% endblock styles %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link1="active" %}
{% endblock nav %}

{% block body %}

<div class="row">

  {% for listing in listings %}

  {% if forloop.counter0 == 0 or forloop.counter0|divisibleby:'10' %}
  <div class="col-4">
    <div class="list-group">
      {% endif %}

      <a class="list-group-item list-group-item-action mb-2"
         href="{% url 'auctions:detail_listing' listing.id %}">{{ listing.title }}</a>

      {% if forloop.counter|divisibleby:'10' %}
    </div>
  </div>
  {% endif %}

  {% empty %}
  <h4>No listings for {{ name }}</h4>
  {% endfor %}

</div>



{% endblock body %}

project2/commerce/auctions/templates/auctions/detail_listing.html
{% extends 'auctions/layout.html' %}
{% load static %}
{% load wiki_filters %}


{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/listing.css' %}">
{% endblock styles %}

{% block body %}

<div class="row">

  {% comment %} LISTING INFORMATION {% endcomment %}
  <div class="col-7 card card-body">

    <h2 class="card-title mb-3">{{ listing.title }}</h2>

    <p class="mb-1">{{ listing.description }}</p>

    <div class="col-6">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Listed at {{ listing.pub_date }}</li>
        <li class="list-group-item">Vendor: <a
             href="{% url 'auctions:user_listings' listing.vendor.id %}">{{ listing.vendor }}</a>
        </li>
        {% if listing.category %}
        <li class="list-group-item">Category:
          <a
             href="{% url 'auctions:category_listing' listing.category.id %}">{{ listing.category }}</a>
        </li>
        {% else %}
        <li class="list-group-item">Category: No Category</li>
        {% endif %}
      </ul>
    </div>

  </div>

  {% comment %} PRICE TAG AND FORMS {% endcomment %}
  <div class="col-3 ml-5">
    {% comment %} WATCHLIST CHECK {% endcomment %}
    {% if user.is_authenticated and user != listing.vendor %}

    <form class="mb-4" action="{% url 'auctions:watch' listing.id %}" method="post">

      {% csrf_token %}
      {% if listing not in user.watchlist.all %}
      <input type="hidden" name="watch" id="watch" value="1">
      <input class="btn btn-primary" type="submit" value="Add to Watchlist">
      {% else %}
      <input type="hidden" name="watch" id="watch" value="0">
      <input class="btn btn-primary" type="submit" value="Remove from Watchlist">
      {% endif %}

    </form>

    {% endif %}


    {% if match_bidder and not listing.active %}
    <p class="alert alert-success" id="detail-price-tag">Price: ${{ listing.price }}</p>
    <p class="winner">Congratulations. You won the auction for the price ${{ listing.price }}</p>
    {% elif match_bidder %}
    <p class="alert alert-info" id="detail-price-tag">Price: ${{ listing.price }}</p>
    <p class="match-bidder">{{ listing.bid_set.count }} Bid(s). Your bid is the highest</p>
    {% else %}
    <p class="alert alert-info" id="detail-price-tag">Price: ${{ listing.price }}</p>
    <p>{{ listing.bid_set.count }} Bid(s)</p>
    {% endif %}

    {% if user.is_authenticated %}

    {% if listing.vendor == user %} {# VENDOR MANAGER #}

    {% if listing.active %}
    <a href="{% url "auctions:close_listing" listing.id %}" class="btn btn-primary">Close
      Listing</a>
    {% else %}
    <button class="btn btn-primary" disabled>Listing closed</button>
    {% endif %}

    <a href="{% url "auctions:edit_listing" listing.id %}" class="btn btn-primary">Edit
      Listing</a>

    {% else %} {# ENDS VENDOR MANAGER #}

    {# BID FORM #}
    {% if listing.active %}
    <form action="{% url 'auctions:bid_listing' listing.id %}" method="post">
      {% csrf_token %}

      {% for hidden in bid_form.hidden_fields %}
      {{ hidden }}
      {% endfor %}

      {% for field in bid_form.visible_fields %}
      <div class="form-group">
        <div class="row ml-0 bid-input">
          <label for="{{ field.id_for_label }}">$</label>
          {{ field | add_class:"form-control"}}
        </div>
        {{ field.errors }}
      </div>
      {% endfor %}
      <input class="btn btn-primary" type="submit" value="Place Bid">
    </form>
    {% endif %}

    {% endif %}

    {% endif %}

  </div>
</div>

<hr>

{% comment %} LISTING IMAGE {% endcomment %}
<div class="row justify-content-center">
  <div class="listing-img detail">
    {% if listing.image %}
    <img src="{{ listing.image }}" alt="Listing Image">
    {% else %}
    <img src="{% static 'auctions/default.jpg' %}" alt="Listing Image">
    {% endif %}
  </div>
</div>

{% comment %} COMMENT FORM {% endcomment %}
<h3 class="mt-4">Comments</h3>
<div class="row">

  <div class="col-6">
    {% if user.is_authenticated %}

    {# COMMENT FORM #}
    <form action="{% url 'auctions:comment_listing' listing.id %}" method="post">
      {% csrf_token %}
      {% include 'auctions/form_snippet.html' with form=comment_form no_label=1 %}
      <input class="btn btn-primary" type="submit" value="Post comment">
    </form>

    {% endif %} {# END AUTHENTICATED #}

  </div>

</div>

{% comment %} COMMENT SECTION {% endcomment %}
<div class="mt-3 mb-5">
  {% for comment in comments %}
  <div class="col-8 card comment mb-2">
    <p class="card-title"><strong>{{ comment.author }}</strong></p>
    <hr>
    <p class="card-text">{{ comment.post }}</p>
    <small class="text-muted">Posted {{ comment.post_date }}</small>
  </div>
  {% empty %}
  <p>No comments to show for this listing</p>
  {% endfor %}
</div>


{% endblock body %}

project2/commerce/auctions/templates/auctions/edit_listing.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/forms.css' %}">
{% endblock styles %}

{% block scripts %}
<script src="{% static 'auctions/labelUpdate.js' %}" defer></script>
{% endblock scripts %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link3="active" %}
{% endblock nav %}

{% block body %}

<h2 class="text-center">Listing: {{ listing.title }}</h2>

<p class="text-center">Current Listing Image</p>
<div class="row justify-content-center mb-5">
  <div class="listing-img detail edit">
    {% if listing.image %}
    <img src="{{ listing.image }}" alt="Listing Image">
    {% else %}
    <img src="{% static 'auctions/default.jpg' %}" alt="Listing Image">
    {% endif %}
  </div>
</div>

<form enctype='multipart/form-data' action="{% url 'auctions:edit_listing' listing.id %}"
      method="post">
  {% csrf_token %}
  {% include 'auctions/form_snippet_listing.html' %}
  <div class="row mt-5 mb-5 justify-content-center">
    <input class="btn btn-primary" type="submit" value="Update Listing">
  </div>
</form>

{% endblock body %}

project2/commerce/auctions/templates/auctions/form_snippet.html
{% load wiki_filters %}

{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}

{# Include the visible fields #}
{% for field in form.visible_fields %}
<div class="form-group">

  {% if no_label %}
  {% else %}
  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
  {% endif %}


  {{ field | add_class:"form-control"}}
  {% if field.help_text %}
  <small class="form-text text-muted">{{ field.help_text | safe }}</small>
  {% endif %}
  {{ field.errors }}

</div>
{% endfor %}

project2/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link3="active" %}
{% endblock nav %}

{% block body %}

<h2 class="mb-4">Login</h2>

{% if message %}
<p class="alert alert-danger col-4">{{ message }}</p>
{% endif %}

<form action="{% url 'auctions:login' %}" method="post">
  {% csrf_token %}
  <div class="form-group row col-6">
    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
  </div>
  <div class="form-group row col-6">
    <input class="form-control" type="password" name="password" placeholder="Password">
  </div>
  <input class="btn btn-primary" type="submit" value="Login">
</form>

<div class="mt-3">
  Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
</div>


{% endblock %}

project2/commerce/auctions/templates/auctions/nav_snippet.html
<nav class="nav nav-pills">
  <a class="nav-link {{ link0 }}" href="{% url 'auctions:index' %}">Active Listings</a>
  <a class="nav-link {{ link1 }}" href="{% url 'auctions:categories' %}">Categories</a>

  {% if user.is_authenticated %}

  <a class="nav-link {{ link2 }}" href="{% url 'auctions:user_listings' user.id %}">My Listings</a>
  <a class="nav-link {{ link3 }}" href="{% url 'auctions:new_listing' %}">New Listing</a>
  <a class="nav-link {{ link4 }}" href="{% url 'auctions:watchlist' %}">Watchlist</a>
  <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>

  {% else %}

  <a class="nav-link {{ link2 }}" href="{% url 'auctions:register' %}">Register</a>
  <a class="nav-link {{ link3 }}" href="{% url 'auctions:login' %}">Log In</a>

  {% endif %}
</nav>

project2/commerce/auctions/templates/auctions/new_listing.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/forms.css' %}">
{% endblock styles %}

{% block scripts %}
<script src="{% static 'auctions/labelUpdate.js' %}" defer></script>
{% endblock scripts %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link3="active" %}
{% endblock nav %}

{% block body %}
<form enctype='multipart/form-data' action="{% url 'auctions:new_listing' %}" method="post">
  {% csrf_token %}
  {% include 'auctions/form_snippet_listing.html' %}
  <div class="row mt-5 mb-5 justify-content-center">
    <input class="btn btn-primary" type="submit" value="Submit New Listing">
  </div>
</form>
{% endblock body %}

project2/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block nav %}
{% include 'auctions/nav_snippet.html' with link2="active" %}
{% endblock nav %}

{% block body %}

<h2 class="mb-4">Register</h2>

{% if message %}
<p class="alert alert-danger col-3">{{ message }}</p>
{% endif %}

<form action="{% url 'auctions:register' %}" method="post">
  {% csrf_token %}
  <div class="form-group row col-6">
    <input class="form-control" autofocus type="text" name="username" placeholder="Username">
  </div>
  <div class="form-group row col-6">
    <input class="form-control" type="email" name="email" placeholder="Email Address">
  </div>
  <div class="form-group row col-6">
    <input class="form-control" type="password" name="password" placeholder="Password">
  </div>
  <div class="form-group row col-6">
    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
  </div>
  <input class="btn btn-primary" type="submit" value="Register">
</form>

<div class="mt-3">
  Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
</div>

{% endblock %}

project2/commerce/auctions/templates/auctions/user_listings.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'auctions/links.css' %}">
{% endblock styles %}

{% block nav %}
{% if user.id == user_id %}
{% include 'auctions/nav_snippet.html' with link2="active" %}
{% else %}
{% include 'auctions/nav_snippet.html' %}
{% endif %}
{% endblock nav %}

{% block body %}


{% for listing in user_listings %}

<div class="row mb-2">

  <div class="col-4">
    <div class="list-group align-items-center">

      <a href="{% url 'auctions:detail_listing' listing.id %}"
         class="list-group-item list-group-item-action">{{ listing.title }}</a>

    </div>
  </div>

  {% if listing.active %}

  <div class="col-4 d-flex align-items-center p-0">
    <a href="{% url "auctions:close_listing" listing.id %}" class="btn btn-primary">Close
      Listing</a>
  </div>

  {% else %}
  <div class="col-4 d-flex align-items-center p-0">
    <p class="alert alert-danger mb-0">Listing Closed</p>
    <a href="{% url "auctions:delete_listing" listing.id %}" class="btn btn-primary ml-3">Delete
      Listing</a>
  </div>
  {% endif %}

</div>
{% empty %}
<h4>You dont have any posted listing</h4>
{% endfor %}


{% endblock body %}